# Generated by Django 4.0.3 on 2022-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userinfo_first_name_alter_userinfo_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='/images/no_avatar.png', null=True, upload_to='images', verbose_name='Аватар'),
        ),
    ]
