# Generated by Django 4.0.3 on 2022-05-17 16:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='/images/no_avatar.png', null=True, upload_to=users.models.user_images_directory_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Фамилия'),
        ),
    ]
